config/routes.rb
Paymeback::Application.routes.draw do


  get "debts/mydebts"

  ActiveAdmin.routes(self)
  

  devise_for :users

  resources :debts, :usergroups, :usdollar

  root :to => "debts#index"
end

app/models/debt.rb
class Debt < ActiveRecord::Base
  include ActiveModel::Validations

  belongs_to :debitor, :class_name => "User", :foreign_key => 'debitor_id'
  belongs_to :creditor, :class_name => "User", :foreign_key => 'creditor_id'
  alias_attribute :expiration_date,:ex_date
    attr_accessible :ex_date,:bill,:bill_file_name,:bill_content_type,:bill_file_size,:bill_updated_at,:cleared, :creditor_id, :debitor_id, :description, :value, :confirmed

  has_attached_file :bill, :storage => :dropbox,:dropbox_credentials => "#{Rails.root}/config/dropbox.yml",:dropbox_options => {:unique_filename => true}

  validates :debitor_id,:value,:description, :presence => true
  validates_attachment :bill, :content_type => { :content_type => ["image/jpg","image/png","image/jpeg","application/pdf"] },
  :size => { :in => 0..500.kilobytes }

  validates_with DateValidator
end

app/controllers/debts_controller.rb
require 'rubygems'

class DebtsController < ApplicationController
  #necessary for authorization, loads authorization for whole application
  load_and_authorize_resource
  # GET /debts
  # GET /debts.json

  def index
    if current_user
    	@debts = Debt.paginate(:page => params[:page], :per_page => 10)
    	respond_to do |format|
      	format.html # index.html.erb
      	format.json { render json: @debts }
    	end
    end
  end

  def mydebts
    if current_user
    	@debts = Debt.all
    	respond_to do |format|
      	format.html # mydebts.html.erb
      	format.json { render json: @debts }
    	end
    end
  end

  # GET /debts/1
  # GET /debts/1.json
  def show
    #@debt = Debt.find(params[:id])
	
	@dollar = (Exchange.find(1).value * Debt.find(params[:id]).value).round(2)
	@yen = (Exchange.find(2).value * Debt.find(params[:id]).value).round(2)
	@pound = (Exchange.find(3).value * Debt.find(params[:id]).value).round(2)
	@rubbel = (Exchange.find(4).value * Debt.find(params[:id]).value).round(2)
	@bitcoin =  (Exchange.find(5).value * @dollar).round(2)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @debt }
    end
  end

  # GET /debts/new
  # GET /debts/new.json
  def new
    @debt = Debt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @debt }
    end
  end

  # GET /debts/1/edit
  def edit
    #@debt = Debt.find(params[:id])
  end

  # POST /debts
  # POST /debts.json
  def create
    @debt = Debt.new(params[:debt])

    respond_to do |format|
      if @debt.save
        format.html { redirect_to @debt, notice: 'Debt was successfully created.' }
        format.json { render json: @debt, status: :created, location: @debt }
      else
        format.html { render action: "new" }
        format.json { render json: @debt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /debts/1
  # PUT /debts/1.json
  def update
    @debt = Debt.find(params[:id])

    respond_to do |format|
      if @debt.update_attributes(params[:debt])
        format.html { redirect_to @debt, notice: 'Debt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @debt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /debts/1
  # DELETE /debts/1.json
  def destroy
    @debt = Debt.find(params[:id])
    @debt.destroy

    respond_to do |format|
      format.html { redirect_to debts_url,notice:'Debt was successfully deleted'}
      format.json { head :no_content }
    end
  end
end

app/helpers/debts_helper.rb
module DebtsHelper
	@cyclecounter = 0
	@cyclemax = 3 #(1 = 3er Ketten, 2 = 4er Ketten ...)

	def self.killoldandcreatenew
		dellist
		createlist
	end

	def self.dellist
		x = Debtniceview.count
		y=0
		while y < x
			todel = Debtniceview.first
			todel.destroy
			y += 1
		end
	end

	def self.dellist2
		x = Debtcycle.count
		y=0
		while y < x
			todel = Debtcycle.first
			todel.destroy
			y += 1
		end
	end

	# in killdoubles werden alle Einträge, bei denen Schuldner 
	# und Gläubiger gleich sind aussortiert
	def self.killdoublesandcross
		dellist
		killthem
		killthecross
	end

	# in killthem werden  AA -> BB Beziehungen gekillt
	def self.killthem
		# zunächst werden die Daten der aktuellen Debtniceview in Arrays gepackt
		data =  Debt.select("value, debitor_id, creditor_id,cleared").where(:cleared => false)
		valuearray = data.select('value').map{|elem|elem.value}
		debitorarray = data.select('debitor_id').map{|elem|elem.debitor_id}
		creditorarray = data.select('creditor_id').map{|elem|elem.creditor_id}

		# nun werden Einträge, bei denen Schuldner und Gläubiger gleich sind gesucht
		# die Schulden werden zusammengerechnet
		x = valuearray.size
		z = 0
		y = 1
		while z < x-1
			while y < x
				# Abfrage, ob Person A Person B mehrfach etwas schuldet
				if debitorarray[z] == debitorarray[y] && creditorarray[z] == creditorarray[y]
					valuearray[z] += valuearray[y]
					valuearray[y] = 0
				end
				y += 1
			end
			z += 1
			y = z + 1
		end

		# Hier werden alle Werte in die Zwischentabelle geschrieben, 
		#	bei denen value != 0 ist
		a = valuearray.size
		b=0
		while b < a
			if valuearray[b] != 0
				debtniceview = Debtniceview.new
				debtniceview.value = valuearray[b]
				debtniceview.debitor_id = debitorarray[b]
				debtniceview.creditor_id = creditorarray[b]
				debtniceview.save
			end
			b += 1
		end
	end

	# in killthecross werden  AB -> BA Beziehungen gekillt
	def self.killthecross
		# zunächst werden die Daten der aktuellen Debtniceview in Arrays gepackt
		data = Debtniceview.select("value, debitor_id, creditor_id")
		valuearray = data.select('value').map{|elem|elem.value}
		debitorarray = data.select('debitor_id').map{|elem|elem.debitor_id}
		creditorarray = data.select('creditor_id').map{|elem|elem.creditor_id}

		# nun wird die bisherige Liste gelöscht
		dellist
		
		# nun werden Einträge, bei denen Schuldner und Gläubiger gleich sind gesucht
		# die Schulden werden zusammengerechnet
		x = valuearray.size
		z = 0
		y = 1
		while z < x-1
			while y < x
				# Abfrage, ob Person A Person B und Person B Person A etwas schuldet
				if debitorarray[z] == creditorarray[y] && creditorarray[z] == debitorarray[y]
					if valuearray[z] > valuearray[y]
						valuearray[z] -= valuearray[y]
						valuearray[y] = 0
					else
						valuearray[y] -= valuearray[z]
						valuearray[z] = 0
					end
				end
				y += 1
			end
			z += 1
			y = z + 1
		end
		# Hier werden alle Werte in die Zwischentabelle geschrieben, 
		#	bei denen value != 0 ist
		a = valuearray.size
		b=0
		while b < a
			if valuearray[b] != 0
				debtniceview = Debtniceview.new
				debtniceview.value = valuearray[b]
				debtniceview.debitor_id = debitorarray[b]
				debtniceview.creditor_id = creditorarray[b]
				debtniceview.save
			end
			b += 1
		end
	end

	# Ab hier startet die Kreisverrechnung
	def self.circle
		data = Debtniceview.select("value, debitor_id, creditor_id")
		$valuearray = data.select('value').map{|elem|elem.value}
		$debitorarray = data.select('debitor_id').map{|elem|elem.debitor_id}
		$creditorarray = data.select('creditor_id').map{|elem|elem.creditor_id}

		w = 0
		while w < $valuearray.size
			# Start debitor und creditor werden eingestellt
			if $valuearray[w] != 0
				debitor = $debitorarray[w]
				creditor = $creditorarray[w]
				x = 0
				while x < $valuearray.size
					# Die Gleichheit von Startcreditor und [x] Debitor wird verglichen
					if creditor == $debitorarray[x]
						#STEP BY STEP !!!!!
						xyzarray = [w,x]
						$cyclecounter=0
						cyclestep(debitor, xyzarray)
					end
					x += 1
				end
				w += 1
			end
		end
	# Nach dem Durchlauf kann aus den Arrays wieder in eine Tabelle geschrieben werden
		dellist2 # vorab löschen
		a = $valuearray.size
		b=0
		while b < a
			if $valuearray[b] != 0
				debtcycle = Debtcycle.new
				debtcycle.value = $valuearray[b]
				debtcycle.debitor_id = $debitorarray[b]
				debtcycle.creditor_id = $creditorarray[b]
				debtcycle.save
			end
			b += 1
		end
	end

# Prüfung, ob in einer Situation ein Kreis vorliegt
	def self.cyclestep(debitor, xyzarray)
		debitor2 = $creditorarray[xyzarray[xyzarray.size-1]]
		y = 0
		while y < $valuearray.size
			xyzarray += [y]
			# Bei true wird nun jeder Schuldner/Gläubiger gesuchtt
			if debitor2 == $debitorarray[y]
				# Falls dieser auch Schulden/Guthaben beim Startdebitorhat
				# liegt ein Dreieck vor
				if debitor == $creditorarray[y]
					# Dreieck gefunden: 
					# Der niedrigste Schuldenstand wird allen abgezogen				
					#cyclevaluewriter(xyzarray)
					cyclevaluewriter(xyzarray)
				else
					# Kein Dreieck, aber vllt ein Viereck!
					@cyclecounter += 1
					if @cyclecounter < @cyclemax
						cyclestep(debitor, xyzarray)
					# Selbstaufruf!
					end	
					@cyclecounter -= 1
				end
			end
			xyzarray.delete_at(xyzarray.size-1)
			y += 1				
		end
	end

	def self.cyclevaluewriter(xyzarray)
		# Zunächst wird der kleinste Wert ermittelt
		v = 1
		minvalue = $valuearray[xyzarray[0]]		
		while v < xyzarray.size
			if $valuearray[xyzarray[v]] < minvalue
				minvalue = $valuearray[xyzarray[v]]		
			end	
			v += 1
		end
		# Nun wird der kleinste Wert abgezogen
		# Hierbei muss es sich um den ersten Wert handeln!
		# Jede mögliche Schulden-Kombination wird durchgegangen.
		# Für eine Kette darf aber nur einmal ein Betrag abgezogen werden
		if minvalue == $valuearray[xyzarray[0]]
			u = 0
			while u < xyzarray.size
				$valuearray[xyzarray[u]] -= minvalue
				u += 1
			end
		end
	end
end

app/views/debts/_form.html.erb
<%= form_for(@debt) do |f| %>
  <% if @debt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@debt.errors.count, "error") %> prohibited this debt from being saved:</h2>

      <ul>
      <% @debt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
   <div class="field">
    <%= f.label :debitor_id %><br />
    <%= f.collection_select :debitor_id, User.where("id !=" + current_user.id.to_s), :id, :nickname, { selected: @debt.debitor_id}, { multiple: false } %>
   </div>
   <div class="field" style="display:none">
    <%= f.label :creditor_id %><br />
    <%= f.number_field :creditor_id, value: current_user.id %>
  </div>
  <div class="field">
    <%= f.label :cleared %><br />
    <%= f.check_box :cleared %>
  </div>
 <div class="field">
    <%= f.label :ex_date %><br />
    <%= f.date_select(:ex_date,:start_year => Time.now.year,:order => [:day,:month,:year],:include_blank => true,:use_month_numbers => true,:default => 2.days.from_now) %>
  </div>
  <div class="field">
    <p style="color:red">The following data types are allowed: JPG,JPEG,PNG,PDF</p>
    <%= f.label :bill %><br />
    <%= f.file_field :bill %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/debts/edit.html.erb
<h1>Editing debt</h1>

<%= render 'form' %>

<%= link_to 'Show', @debt %> |
<%= link_to 'Back', debts_path %>

app/views/debts/index.html.erb
<!-- Checks if a user is logged in -->
<% if current_user %>
<h3>Total debt list:</h3>

<table class="table table-hover table-condensed">
  <tr>
    <th>Value</th>

    <th>Description</th>
    <th>Debitor</th>
    <th>Creditor</th>
    <!--<th>Cleared</th>-->
    <th>Expiration Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
	
	<%= will_paginate @debts %>
	<% @debts.each do |debt| %>

<tr>

    <td><%= debt.value %></td>
    <td><%= debt.description %></td>
    <td><%= debt.debitor.nickname %></td>
    <td><%= debt.creditor.nickname %></td>
    <!--<td><%= debt.cleared %></td>-->
  <% if debt.cleared %>
<td style="background-color:green">
  <% elsif  debt.ex_date != nil && debt.ex_date < Date.today%>
<td style="background-color:red">
  <% elsif  debt.ex_date != nil && debt.ex_date < (Date.today+7) %>
<td style="background-color:orange">
<% else %>
<td style="background-color:yellow">
  <%end%>

<% if debt.ex_date != nil  %> 
 <%= debt.ex_date.strftime('%d.%m.%Y') %>
 <% else  %>Not set<% end %></td>
    <td><%= link_to 'Show', debt %></td>
    <td><%= link_to 'Edit', edit_debt_path(debt) %></td>	
    <td><% if ((debt.creditor_id == current_user.id) and debt.cleared);if can?(:destroy, Debt)%>
	<%= link_to 'Destroy', debt, method: :delete, data: { confirm: 'Are you sure?' }%><%end;end%>
    </td>
  <%end%>
  </tr>
</table>

<!-- Calling the allocation methods-->
<%= DebtsHelper.killdoublesandcross %>
<%= DebtsHelper.circle %>

<!-- Table after solving direct equalities and crossings-->
<h3>Here's the table after solving direct equalities and crossing:</h3>
<% Debtniceview.where('').each do |debtniceview| %>
<%= User.find(debtniceview.debitor_id).nickname %> owes <%= User.find(debtniceview.creditor_id).nickname %> <%= debtniceview.value %> €.</br> 
<%end%>

<!-- Table after resolution of debt circles.-->
<h3>Table after resolution of debt circles:</h3>
<% Debtcycle.where('').each do |debtcycle| %>

<%= User.find(debtcycle.debitor_id).nickname %> owes <%= User.find(debtcycle.creditor_id).nickname %> <%= debtcycle.value %> €.</br> 
<%end%>

<h3>That means for you:</h3>
<% Debtcycle.where('debitor_id = ?', current_user.id).each do |debtcycle| %>
You owe <%= User.find(debtcycle.creditor_id).nickname %> <%= debtcycle.value %> €.</br> 
<%end%>
<% Debtcycle.where('creditor_id = ?', current_user.id).each do |debtcycle| %>
<%= User.find(debtcycle.debitor_id).nickname %> owes you <%= debtcycle.value %> €.</br> 
<%end%>
<%end%>
<br />

app/views/debts/mydebts.html.erb
<!-- Checks if a user is logged in -->
<% if current_user %>
<h3>My debts as creditor:</h3>

<table class="table table-hover table-condensed">
  <tr>
    <th>Value</th>

    <th>Description</th>
    <th>Debitor</th>
    <th>Creditor</th>
    <!--<th>Cleared</th>-->
    <th>Expiration Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
	

	<% Debt.where('creditor_id = ?', current_user.id).each do |debt| %>

<tr>

    <td><%= debt.value %></td>
    <td><%= debt.description %></td>
    <td><%= debt.debitor.nickname %></td>
    <td><%= debt.creditor.nickname %></td>
    <!--<td><%= debt.cleared %></td>-->  <% if debt.cleared %>
<td style="background-color:green">
  <% elsif  debt.ex_date != nil && debt.ex_date < Date.today%>
<td style="background-color:red">
  <% elsif  debt.ex_date != nil && debt.ex_date < (Date.today+7) %>
<td style="background-color:orange">
<% else %>
<td style="background-color:yellow">
  <%end%>

<% if debt.ex_date != nil  %> 
 <%= debt.ex_date.strftime('%d.%m.%Y') %>
 <% else  %>Not set<% end %></td>
    <td><%= link_to 'Show', debt %></td>
    <td><%= link_to 'Edit', edit_debt_path(debt) %></td>	
    <td><% if ((debt.creditor_id == current_user.id) and debt.cleared);if can?(:destroy, Debt)%>
	<%= link_to 'Destroy', debt, method: :delete, data: { confirm: 'Are you sure?' }%><%end;end%>
    </td>
  <%end%>
  </tr>
</table>


<h3>My debts as debitor:</h3>

<table class="table table-hover table-condensed">
  <tr>
    <th>Value</th>

    <th>Description</th>
    <th>Debitor</th>
    <th>Creditor</th>
    <!--<th>Cleared</th>-->
    <th>Expiration Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
	

	<% Debt.where('debitor_id = ?', current_user.id).each do |debt| %>

<tr>

    <td><%= debt.value %></td>
    <td><%= debt.description %></td>
    <td><%= debt.debitor.nickname %></td>
    <td><%= debt.creditor.nickname %></td>
    <!--<td><%= debt.cleared %></td>-->
  <% if debt.cleared %>
<td style="background-color:green">
  <% elsif  debt.ex_date != nil && debt.ex_date < Date.today%>
<td style="background-color:red">
  <% elsif  debt.ex_date != nil && debt.ex_date < (Date.today+7) %>
<td style="background-color:orange">
<% else %>
<td style="background-color:yellow">
  <%end%>

<% if debt.ex_date != nil  %> 
 <%= debt.ex_date.strftime('%d.%m.%Y') %>
 <% else  %>Not set<% end %></td>
    <td><%= link_to 'Show', debt %></td>
    <td><%= link_to 'Edit', edit_debt_path(debt) %></td>	
    <td><% if ((debt.creditor_id == current_user.id) and debt.cleared);if can?(:destroy, Debt)%>
	<%= link_to 'Destroy', debt, method: :delete, data: { confirm: 'Are you sure?' }%><%end;end%>
    </td>
  <%end%>
  </tr>
</table>



<h3>Für Dich heißt das:</h3>
<% Debtcycle.where('debitor_id = ?', current_user.id).each do |debtcycle| %>
Du schuldest <%= User.find(debtcycle.creditor_id).nickname %> noch <%= debtcycle.value %> €.</br> 
<%end%>
<% Debtcycle.where('creditor_id = ?', current_user.id).each do |debtcycle| %>
<%= User.find(debtcycle.debitor_id).nickname %> schuldet Dir noch <%= debtcycle.value %> €.</br> 
<%end%>
<%end%>
<br />

app/views/debts/new.html.erb
<h1>New debt</h1>

<%= render 'form' %>

<%= link_to 'Back', debts_path %>

app/views/debts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Value:</b>
  <%= @debt.value %>
</p>
<p>
  <b>Value other currency </b><br>
Last update: <%= Exchange.find(1).updated_at.to_s(:short)%> (UTC) <br>
  <%= @dollar %> (US-Dollar)<br>
	<%= @yen  %> (Yen) <br>
	<%= @pound   %> (Pound)<br>
	<%= @rubbel  %> (Rubbel) <br>	
	<%= @bitcoin  %> (Bitcoin) 
	
</p>
<p>
  <b>Description:</b>
  <%= @debt.description %>
</p>

<p>
  <b>Debitor:</b>
  <%= @debt.debitor.nickname %>
</p>

<p>
  <b>Creditor:</b>
  <%= @debt.creditor.nickname %>
</p>

<p>
  <b>Cleared:</b>
  <%= @debt.cleared %>
</p>

<p>
  <b>Expiration Date:</b>
  <%= if @debt.ex_date != nil;@debt.ex_date.strftime('%d.%m.%Y');end %>
</p>
<p>
  <b>Bill:</b>
	<%= if @debt.bill_file_name != nil
  		link_to 'Get File', @debt.bill.url(:download => true) 
	    end 
        %>
</p>
<%= link_to 'Edit', edit_debt_path(@debt) %> |
<%= link_to 'Back', debts_path %>